proverbs = [
    "A bad excuse is better then none.",
    "A bad penny always comes back.",
    "A bad workman blames his tools.",
    "A bird makes his nest little by little.",
    "A bully is always a coward.",
    "A cat has nine lives.",
    "A chain is no stronger than its weakest link.",
    "A change is as good as a rest.",
    "A closed mouth gathers no foot.",
    "A drowning man will clutch at a straw.",
    "A fool in a gown is none the wiser.",
    "A fool uttereth all his mind.",
    "A friend is easier lost than found.",
    "A friend to everybody is a friend to nobody.",
    "A good conscience is a soft pillow.",
    "A good friend is one's nearest relation.",
    "A good reputation is a fair estate.",
    "A good thing is all the sweeter when won with pain.",
    "A good thing is soon snatched up.",
    "A hair on the head is worth two in the brush.",
    "A handsome shoe often pinches the foot.",
    "A light purse makes a heavy heart.",
    "A little body doth often harbour a great soul.",
    "A little each day is much in a year.",
    "A little knowledge is a dangerous thing.",
    "A loveless life is a living death.",
    "A man too careful of danger lives in continual torment.",
    "A man's intentions seldom add to his income.",
    "A penny saved is a penny earned.",
    "A point is the beginning of magnitude.",
    "A poor man is better than a liar.",
    "A problem shared is a problem halved.",
    "A rolling stone gathers no moss.",
    "A short cut is often a wrong cut.",
    "A single penny fairly got is worth a thousand that are not.",
    "A spark can start a great fire.",
    "A stitch in time saves nine.",
    "A throne is only a bench covered in purple velvet.",
    "A wink is as good as a nod, to a blind man.",
    "A wise man doesn't need advice, and a fool won't take it.",
    "Absence makes the fond heart wander.",
    "Accidents will happen.",
    "Adversity and loss make a man wise.",
    "Adversity flatters no man.",
    "Advice when most needed is least heeded.",
    "After dinner rest a while, after supper walk a mile.",
    "After the storm comes the calm.",
    "All aren't hunters that blow the horn.",
    "All cats are grey in the dark.",
    "All promises are either broken or kept.",
    "All things come to those that wait.",
    "All work and no play makes Jack a dull boy.",
    "All's fair in love and war.",
    "All's well that ends well.",
    "Always in a hurry, always behind.",
    "Always you are to be rich next year.",
    "An elephant never forgets.",
    "An eye for an eye and a tooth for a tooth.",
    "An idle man is the devil's playfellow.",
    "An old fox need learn no craft.",
    "An onion a day keeps everyone away.",
    "An open door may tempt a saint.",
    "Anger and hate hinder good counsel.",
    "Angry words fan the fire like wind.",
    "Appearances are deceptive.",
    "As fit as a fiddle.",
    "As green as grass.",
    "As hard as nails.",
    "As is the gardener so is the garden.",
    "As one door closes, another always opens.",
    "As sick as a dog.",
    "As you sow, so shall you reap.",
    "Ask and you shall receive.",
    "Ask no questions and hear no lies.",
    "At a round table there's no dispute about the place.",
    "Attack is the best form of defense.",
    "Beauty is but skin deep.",
    "Beauty is in the eye of the beholder.",
    "Before you meet the handsome prince you have to kiss a lot of toads.",
    "Behind every great man stands a strong woman.",
    "Best to bend it while it's a twig.",
    "Better to go back than go wrong.",
    "Better to have loved and lost, than to have never loved at all.",
    "Better to have than to wish.",
    "Better to wear out than rust out.",
    "Big fish eat little fish.",
    "Bread never falls but on its buttered side.",
    "Brevity is the soul of wit.",
    "Business before pleasure.",
    "By hook or by crook.",
    "Call a spade a spade.",
    "Change is inevitable, except from vending machines.",
    "Cheerfulness smooths the road of life.",
    "Cleanliness is next to Godliness.",
    "Clothes make the man.",
    "Cold hands, warm heart.",
    "Conscience makes cowards of us all.",
    "Credit won by lying is quick in dying.",
    "Curiosity killed the cat; Satisfaction brought it back.",
    "Curses, like chickens come home to roost.",
    "Cut off one's nose to spite one's face.",
    "Cut your coat according to the cloth.",
    "Damage suffered makes you knowing, but seldom rich.",
    "Deeds are fruits, words are but leaves.",
    "Desperate diseases must have desperate remedies.",
    "Diamonds are forever.",
    "Different strokes for different folks.",
    "Diligence is the mother of good luck.",
    "Discretion is the better part of valour.",
    "Distance lends enhancement to the view.",
    "Distance makes the heart grow fonder.",
    "Divide and conquer.",
    "Do as I say not as I do.",
    "Do as you would be done by.",
    "Do right and fear no man.",
    "Do unto others as you would have them do to you.",
    "Don't advertise: Tell it to a gossip.",
    "Don't beat a dead horse.",
    "Don't blow your own trumpet.",
    "Don't byte off more than you can view.",
    "Don't change horses in midstream.",
    "Don't count your chickens before they hatch.",
    "Don't cross the bridge till you come to it.",
    "Don't go off half-cocked.",
    "Don't throw the baby out with the bath-water.",
    "Don't try kicking against the wind.",
    "Drink like a fish, water only.",
    "Early to bed, early to rise, makes you healthy, wealthy and wise.",
    "Easy come, easy go.",
    "Empty bags cannot stand upright.",
    "Empty barrels make the most noise.",
    "Empty vessels make the most noise.",
    "Every cloud has a silver lining.",
    "Every dog has its day.",
    "Every man has his price.",
    "Every man is the architect of his destiny.",
    "Every path has its puddle.",
    "Everybody must row with the oars he has.",
    "Everything has an end.",
    "Experience is the best teacher.",
    "Experience is the father of wisdom.",
    "Facts do not cease to exist because they are ignored.",
    "Faint heart never won fair lady.",
    "Fair exchange is no robbery.",
    "Fall seven times. Stand up eight.",
    "False friends are worse than open enemies.",
    "Fax is stranger than fiction.",
    "Few words and many deeds.",
    "First come, first served.",
    "First impressions are the most lasting.",
    "Fools rush in where angels fear to tread.",
    "Fortune favours the brave.",
    "Four eyes are better than two.",
    "Fresh as a daisy.",
    "From trivial things, great contests often arise.",
    "Give credit where credit is due.",
    "Give them an inch and they'll take a mile.",
    "Good company on the road is the shortest cut.",
    "Good wine ruins the purse, and bad wine ruins the stomach.",
    "Gossips are frogs, they drink and talk.",
    "Great groups from little icons grow.",
    "Greediness burst the bag.",
    "Grief divided is made lighter.",
    "Grow angry slowly, there's plenty of time.",
    "Grumbling makes the loaf no larger.",
    "Half a loaf is better than none.",
    "Hard work never did anyone any harm.",
    "Hasty climbers have sudden falls.",
    "Hasty judgements are generally faulty.",
    "Hatred is as blind as love.",
    "He bears misery best that hides it most.",
    "He has enough who is content.",
    "He is rich that is satisfied.",
    "He that hurts another, hurts himself.",
    "He that pays last never pays twice.",
    "He who drinks a little too much drinks much too much.",
    "He who fights and runs away, lives to fight another day.",
    "He who laughs last, laughs longest.",
    "He who rises late must trot all day.",
    "He who sings drives away sorrow.",
    "He who won't be advised, can't be helped.",
    "He who wronged you will hate you.",
    "Heavy givers are light complainers.",
    "His bark is louder than his bite.",
    "His eyes are bigger than his belly.",
    "Home is where the heart is.",
    "Honesty is the best policy.",
    "Hope for the best and prepare for the worst.",
    "Hunger is the best sauce.",
    "I am rubber and you are glue. Your words bounce off me and stick to you.",
    "If a job is worth doing it is worth doing well.",
    "If anything can go wrong, it will.",
    "If at first you don't succeed, skydiving is not for you.",
    "If it's not broken, don't fix it.",
    "If the cap fits, wear it.",
    "If wishes were horses, beggars would ride.",
    "If you can't help, don't hinder.",
    "If you don't say it you will not have to unsay it.",
    "If you lie down with dogs, you'll get up with fleas.",
    "If you lose your temper, don't look for it.",
    "If you tell the truth, you don't have to remember anything.",
    "In for a penny, in for a pound.",
    "In one ear and out the other.",
    "In the country of the blind, the one-eyed man is king.",
    "Innocent as a new born babe.",
    "It is better to be born lucky than rich.",
    "It is better to be green and growing than ripe and rotten.",
    "It is easier to destroy than to build.",
    "It is lonesome in the saddle since the horse died.",
    "It is no use crying over spilt milk.",
    "It is the first step that is difficult.",
    "It takes two to have an argument.",
    "It's a poor job that can't carry one boss.",
    "It's all in a days work.",
    "It's an ill bird that fouls its own nest.",
    "It's either all or nothing.",
    "It's not over till it's over.",
    "Keep your mouth shut and your eyes open.",
    "Kill two birds with the one stone.",
    "Laugh and the world laughs with you. Cry and you cry alone.",
    "Least talk most work.",
    "Leave no stone unturned.",
    "Leave tomorrow till tomorrow.",
    "Let sleeping dogs lie.",
    "Let the buyer beware.",
    "Life begins at forty.",
    "Like a fish out of water.",
    "Like looking for a needle in a haystack.",
    "Listen to the pot calling the kettle black.",
    "Little and often fill the purse.",
    "Little strokes fell great oaks.",
    "Little thieves are hanged, but great ones escape.",
    "Live and learn.",
    "Lost time is never found again.",
    "Love and a cough cannot be hid.",
    "Love does much but money does all.",
    "Love levels all inequalities.",
    "Love makes a good eye squint.",
    "Love sees no faults.",
    "Love to live and live to love.",
    "Man is the head but woman turns it.",
    "Manners maketh the man.",
    "Many a true word spoken in jest.",
    "Many drops make a shower.",
    "Many hands make light work.",
    "Marry in haste, repent at leisure.",
    "Memory is the treasure of the mind.",
    "Mighty oaks from tiny acorns grow.",
    "Modulation in all things.",
    "Money burns a hole in your pocket.",
    "Necessity is a hard nurse, but she raises strong children.",
    "Needs must when the devil drives.",
    "Never judge a book by its cover.",
    "Never let the sun go down on your anger.",
    "Never let the sun set on angry heart.",
    "Never let the sun set on thy wrath.",
    "Never look a gift horse in the mouth.",
    "Never put off 'til tomorrow what you can do today.",
    "Never quarrel with one's bread and butter.",
    "Never spend your money before you have it.",
    "Never test the depth of the water with both feet.",
    "No life can be dreary when work is a delight.",
    "No man is worse for knowing the worst of himself.",
    "No one can be caught in places he does not visit.",
    "No wise man ever wishes to be younger.",
    "Nobody can serve two masters.",
    "Not in a month of Sundays.",
    "Not to break is better than to mend.",
    "Nothing falls into the mouth of a sleeping fox.",
    "Nothing is ill said if it is not ill taken.",
    "Oaks may fall when reeds take the storm.",
    "Old friends and old wine are best.",
    "Once a task has first begun, never quit until it's done.",
    "One false move may lose the game.",
    "One man's loss, is another man's gain.",
    "One man's meat is another man's poison.",
    "One mans junk is another man's treasure.",
    "One of these days is none of these days.",
    "One picture is worth a thousand words.",
    "One today is worth two tomorrows.",
    "Only the good die young.",
    "Open confession is good for the soul.",
    "Out of sight, out of mind.",
    "Out of the frying pan into the fire.",
    "Patience is a virtue.",
    "Peace begins just where ambition ends.",
    "Penny wise, pound foolish.",
    "Pentium wise, pen and paper foolish.",
    "Persuasion is better than force.",
    "Pride cometh before a fall.",
    "Pride feels no pain.",
    "Procrastination is the thief of time.",
    "Putting the cart before the horse.",
    "Ready money is ready medicine.",
    "Rules are made to be broken.",
    "Sauce for the goose is sauce for the gander.",
    "Say what you mean and mean what you say.",
    "See nothing, say nothing, know nothing.",
    "Self praise is no recomendation.",
    "Shake the hand before you plough the field.",
    "Silence is an excellent remedy against slander.",
    "Silence is golden.",
    "Silence is less injurious than a bad reply.",
    "Some of the best gifts come in small packages.",
    "Sound as a bell.",
    "Speak clearly, if you speak at all.",
    "Step by step one goes far.",
    "Sticks and stones may break my bones but words will never hurt me.",
    "Still waters run deep.",
    "Stop beating around the bush.",
    "Strike while the iron's hot.",
    "Talking comes by nature, silence by wisdom.",
    "Temper is so good a thing that we should never lose it.",
    "The beaten path is safest.",
    "The best things are not bought and sold.",
    "The best things come in small packages.",
    "The bigger they are the harder they fall.",
    "The bigger, the better.",
    "The course of love never did run smooth.",
    "The customer is always right.",
    "The darkest hour is before the dawn.",
    "The devil finds work for idle hands.",
    "The early bird gets the worm.",
    "The family that prays together, stays together.",
    "The fool wanders, the wise man travels.",
    "The geek shall inherit the earth.",
    "The gods help them that help themselves.",
    "The golden age never was the present one.",
    "The grass is always greener on the other side.",
    "The harder you work, the luckier you are.",
    "The hardest work is to do nothing.",
    "The hood does not make the monk.",
    "The leopard does not change his spots.",
    "The longer you live the more you see.",
    "The longest journey begins with the first step.",
    "The longest way round is the sweetest way home.",
    "The love of money is the root of all evil.",
    "The meek shall inherit the earth.",
    "The more you stir, the more it stinks.",
    "The second mouse gets the cheese.",
    "The sleepy fox catches no chickens.",
    "The strongest memory is weaker than the palest ink.",
    "The sun shines on both sides of the hedge.",
    "The wise shall understand.",
    "The loudest wheel always gets the grease.",
    "There is a thin line between love and hate.",
    "There is no better looking-glass than an old friend.",
    "There is no honour among thieves.",
    "There's no use in flogging a dead horse.",
    "Those who don't learn from history are doomed to repeat it.",
    "To add insult to injury.",
    "To each his own.",
    "To eat one's heart out.",
    "To err is human, to forgive divine.",
    "To scare a bird is not the way to catch it.",
    "To wait and be patient soothes many a pang.",
    "Tomorrow is a new day.",
    "Too many clicks spoil the browse.",
    "Too many irons in the fire.",
    "True beauty lies within.",
    "Up and down like a fiddler's elbow.",
    "Use not today what tomorrow will need.",
    "Virtual reality is its own reward.",
    "Waste not, want not.",
    "We cannot erase the sad records from our past.",
    "We do not always gain by changing.",
    "What can't be cured must be endured.",
    "Where there's a will there's a way.",
    "Where there's smoke there's fire.",
    "While the cats away the mice play.",
    "While there's life there's hope.",
    "Winners never quit, quitters never win.",
    "Wisdom is better than strength.",
    "Wisdom is neither inheritance nor a legacy.",
    "Wisdom is the wealth of the wise.",
    "Wise it is to comprehend the whole.",
    "Wondrous is the strength of cheerfulness.",
    "You are what you eat.",
    "You aren't learning much when your lips are moving.",
    "You can eat an elephant if you do it one mouthful at a time.",
    "You can't get blood out of a stone.",
    "You can't live on bread alone.",
    "You can't tell a book by its cover.",
    "You can't unscramble a scrambled egg.",
    "You cannot lose what you never had.",
    "You have to crawl before you walk.",
    "You made your bed, now you must lie in it.",
    "You never know what you can do till you try.",
    "You snooze, you lose.",
    "Seize the day.",
    "When it rains, it drains.",
    "The squeaky mouse gets the cheese.",
    "After the feast comes the reckoning.",
    "All that glitters is not gold.",
    "The apple does not fall far from the tree.",
    "Barking dogs seldom bite.",
    "Beauty is in the eyes of the beholder.",
    "Better a live coward than a dead hero.",
    "The bigger they are, the harder they fall.",
    "Clothes don't make the man.",
    "Curiosity killed the cat.",
    "Do as I say, not as I do.",
    "Don't bite off more than you can chew.",
    "Don't count your chickens before they're hatched.",
    "Don't cry over spilled milk.",
    "Don't judge a book by its cover.",
    "Don't judge a man until you've walked in his boots.",
    "Don't look a gift horse in the mouth.",
    "Don't put off for tomorrow what you can do today.",
    "Don't put the cart before the horse.",
    "The first step is always the hardest.",
    "A friend who shares is a friend who cares.",
    "Good things come in small packages.",
    "The grass is always greener on the other side of the fence.",
    "Haste makes waste.",
    "He who laughs last, laughs best.",
    "Hindsight is better than foresight.",
    "If you can't beat them, join them.",
    "If you can't stand the heat, get out of the kitchen.",
    "Imitation is the sincerest form of flattery.",
    "In unity there is strength.",
    "It takes two to tango.",
    "Leave well enough alone.",
    "A leopard can't change its spots.",
    "Lightning never strikes twice in the same place.",
    "Love is blind.",
    "Love makes the world go round.",
    "Man does not live by bread alone.",
    "Might makes right.",
    "Misery loves company.",
    "A miss is as good as a mile.",
    "Money does not grow on trees.",
    "No pain, no gain.",
    "Nothing hurts like the truth.",
    "Nothing ventured, nothing gained.",
    "Old habits die hard.",
    "One good turn deserves another.",
    "One man's gravy is another man's poison.",
    "One swallow does not a summer make.",
    "Possession is nine-tenths of the law.",
    "Practice makes perfect.",
    "The road to hell is paved with good intentions.",
    "The spirit is willing, but the flesh is weak.",
    "Strike while the iron is hot.",
    "There is no honor among thieves.",
    "There is more than one way to skin a cat.",
    "There is no place like home.",
    "Too many chiefs, not enough Indians.",
    "Two's company, but three's a crowd.",
    "The way to a man's heart is through his stomach.",
    "When in Rome, do as the Romans do.",
    "When the cat's away, the mice play.",
    "Where there is smoke, there is fire.",
    "You have to take the good with the bad.",
    "You reap what you sow.",
    "The beef is beef.",
    "The beef gets beef.",
    "The beef not beef.",
    "The beef do beef.",
    "The beef can't beef.",
    "The beef to beef.",
    "The beef makes beef.",
    "There is just one gotcha."
]